<<<<<<< HEAD
# Generated by Django 2.0.2 on 2018-02-28 13:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
=======
# Generated by Django 2.0.2 on 2018-02-25 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> 2a3752844ce80360a4460ba257354c495cdc7e2f


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='CommentsBased',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('comment_text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PostBased',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('post_text', models.CharField(max_length=1500)),
                ('post_date', models.DateTimeField(default=datetime.datetime(2018, 2, 28, 13, 27, 18, 269168, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
=======
>>>>>>> 2a3752844ce80360a4460ba257354c495cdc7e2f
            name='ProfileParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('city', models.CharField(max_length=200)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
<<<<<<< HEAD
        migrations.AddField(
            model_name='commentsbased',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mychar.PostBased'),
=======
        migrations.CreateModel(
            name='SkillsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100, unique=True)),
                ('skill_popularity', models.IntegerField()),
                ('skill_id', models.CharField(max_length=100, unique=True)),
            ],
>>>>>>> 2a3752844ce80360a4460ba257354c495cdc7e2f
        ),
    ]
