# Generated by Django 2.0.7 on 2018-07-28 09:09

from django.db import migrations, models
import mychar.backend


class Migration(migrations.Migration):

    dependencies = [
        ('mychar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charphoto',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', help_text='Profile Picture', null=True, upload_to=mychar.backend.path_and_rename, verbose_name='Profile Picture', width_field='image_width'),
        ),
    ]
