# Generated by Django 2.0.2 on 2018-02-28 13:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mychar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentsbased',
            old_name='author',
            new_name='comment_author',
        ),
        migrations.RenameField(
            model_name='postbased',
            old_name='author',
            new_name='post_author',
        ),
        migrations.AddField(
            model_name='commentsbased',
            name='comment_date',
            field=models.DateField(default=datetime.datetime(2018, 2, 28, 13, 36, 59, 657655, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postbased',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 28, 13, 36, 59, 657655, tzinfo=utc)),
        ),
    ]
