# Generated by Django 2.0.2 on 2018-02-25 10:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mychar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileparams',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='profileparams',
            name='date_of_register',
            field=models.DateField(default=datetime.datetime(2018, 2, 25, 10, 50, 37, 831549, tzinfo=utc)),
        ),
    ]
