# Generated by Django 2.0.2 on 2018-02-25 10:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mychar', '0004_auto_20180225_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileparams',
            name='date_of_register',
            field=models.DateField(default=datetime.datetime(2018, 2, 25, 10, 55, 56, 630582, tzinfo=utc)),
        ),
    ]
