# Generated by Django 2.0.2 on 2018-02-28 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mychar', '0005_auto_20180225_1355'),
        ('mychar', '0002_auto_20180228_1637'),
    ]

    operations = [
    ]
