# Generated by Django 2.0.2 on 2018-02-28 16:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mychar', '0006_merge_20180228_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100, unique=True)),
                ('skill_popularity', models.IntegerField()),
                ('skill_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='commentsbased',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 28, 16, 8, 48, 760179, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postbased',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 28, 16, 8, 48, 759679, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profileparams',
            name='date_of_register',
            field=models.DateField(default=datetime.datetime(2018, 2, 28, 16, 8, 48, 742166, tzinfo=utc)),
        ),
    ]
