# Generated by Django 2.0.2 on 2018-02-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180222_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_based',
            old_name='username',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='user_based',
            name='user_nick',
        ),
        migrations.AddField(
            model_name='user_based',
            name='public_name',
            field=models.CharField(default='Tony Montana', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_based',
            name='user_email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email adress'),
        ),
    ]
