# Generated by Django 2.0.2 on 2018-02-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20180222_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_based',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user_based',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
