# Generated by Django 2.0.2 on 2018-03-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20180223_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_based',
            name='date_of_register',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_based',
            name='original_user_name',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='user_based',
            name='user_city',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_based',
            name='public_name',
            field=models.CharField(max_length=60),
        ),
    ]
